CREATE TABLE [Locations] (
  [Building] TEXT,
  [Location] TEXT,
  [Room Type] TEXT NULL,
  [Mangement] TEXT NULL,
  [Contractor] TEXT NULL,
  [Department] TEXT NULL,
  [Seating Capacity] TEXT NULL,
  [Last Install] TEXT NULL,
  [Hallway Access] TEXT NULL,
  [Access] TEXT NULL,
  [Key Number] TEXT NULL,
  [Key Core] TEXT NULL,
  [Rack Location] TEXT NULL,
  [Rack Key] TEXT NULL,
  [Install Warranty] TEXT NULL,
  [Cost Level] TEXT NULL,
  [Room Cost] TEXT NULL,
  [Network Jacks] TEXT NULL,
  [Open Jacks] TEXT NULL,
  [Video Conference] TEXT NULL,
  [Display] TEXT NULL,
  [PC Model] TEXT NULL,
  [Speakers] TEXT NULL,
  [Number of Speakers] TEXT NULL,
  [Microphone] TEXT NULL,
  [Number of Microphone] TEXT NULL,
  [Pictures] TEXT NULL,
  [Documentation] TEXT NULL,
  [notes] TEXT NULL
);

INSERT INTO [Locations] ([Building],[Location],[Room Type],[Mangement],[Contractor],[Department],[Seating Capacity],[Last Install],[Hallway Access],[Access],[Key Number],[Key Core],[Rack Location],[Rack Key],[Install Warranty],[Cost Level],[Room Cost],[Network Jacks],[Open Jacks],[Video Conference],[Display],[PC Model],[Speakers],[Number of Speakers],[Microphone],[Number of Microphone],[Pictures],[Documentation],[notes])
VALUES
('Agriculture Engineering','AE 101/120','Computer Lab','No AV',NULL,'FABE',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'None Needed',NULL),
('Agriculture Engineering','AE 101A','ETS Storage','ETS',NULL,'ETS',NULL,NULL,NULL,'Key',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'None Needed',NULL),
('Agriculture Engineering','AE 144','Rack Room','ETS','Ohio Valley','FABE','0','2022',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'None Needed','Rack for AE 148'),
('Agriculture Engineering','AE 148','Teaching Lab','ETS','Ohio Valley','FABE','35','2022',NULL,'Key','10','R64B1','In 144','None',NULL,'Level 3',NULL,'2','0','Yes','TV',NULL,'Crestron','6','Biamp','4',NULL,'Done','Rack is in AE 144'),
('Agriculture Engineering','AE 156','Lab','Shared w/ FABE',NULL,'FABE',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'None Needed','Rouge Equipment but will likely need to support'),
('Agriculture Engineering','AE 158','Lab','Shared w/ FABE',NULL,'FABE',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'None Needed','Rouge Equipment but will likely need to support'),
('Agriculture Engineering','AE 166','Teaching Lab','No AV',NULL,'FABE',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'None Needed',NULL),
('Aerospace Research Center','ARC 100','Conference Room','ARC','Ohio Valley','ARC','18','2015*','Yes','Key','0','G87A48X','Podium','None',NULL,'50000',NULL,'1','0','Yes','Motorized Screen',NULL,'Crestron','6','Shure MXA','1',NULL,'Waiting on Zoom Drivers','Really Old Touch Panel (Blue Background)'),
('Aerospace Research Center','ARC 176','Conference Room','ARC','Unknown','ARC','8','2014','Yes','Key','0','G87A4X','None','None',NULL,'15000',NULL,'4','3','No','Dirt Wall',NULL,'Bose','2','None','0',NULL,'None Needed',NULL),
('Baker Systems Engineering','BE 210E','Conference Room','ETS','ETS','ISE','14','2023','No','Key','79','G85B64X','Behind TV','None',NULL,'30000',NULL,'1','0','No','TV',NULL,'TV','1','None','0',NULL,'Needs Updated - Need control panel pic','USB Periferals for video conference'),
('Baker Systems Engineering','BE 210H','Conference Room','ETS','ETS','ISE','8','2017*','No','Key','79','G85B64X','Behind TV','None',NULL,'15000',NULL,'1','0','No','TV',NULL,'TV','0','None','0',NULL,'Needs Updated - Need control panel pic',NULL),
('Baker Systems Engineering','BE 211','Computer Lab','Department','ETS','ISE','50','2014*',NULL,'Lenel',NULL,NULL,'Behind TV','None',NULL,'6000',NULL,'1','1','No','TV',NULL,'TV','0','None','0',NULL,'None Needed',NULL),
('Baker Systems Engineering','BE 310','Teaching Lab','No AV',NULL,'CSE','100',NULL,NULL,'Lenel',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N/A','None',NULL,'None','0','None','0',NULL,'None Needed',NULL),
('Baker Systems Engineering','BE 347/351','Mixed Purpose','ETS','ETS','ISE','30','2015*',NULL,'Lenel','79','M6AC14 | M6AC10 *(347)','Podium','None',NULL,'80000',NULL,'2','1','Yes','Projector',NULL,'TV','4','MXL Boundry','1',NULL,'Done','See system notes in one note'),
('Baker Systems Engineering','BE 348/356','Computer Lab','No AV',NULL,'ISE','20',NULL,NULL,'Lenel',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N/A','None',NULL,'None','0','None','0',NULL,'None Needed',NULL),
('Baker Systems Engineering','BE 364','ETS Storage','ETS',NULL,'ETS',NULL,NULL,NULL,'Swipe Access',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'None Needed',NULL),
('Baker Systems Engineering','BE 378','Computer Lab','No AV',NULL,'ISE','10',NULL,NULL,'Lenel',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N/A','None',NULL,'None','0','None','0',NULL,'None Needed',NULL),
('Baker Systems Engineering','BE 392','ETS Storage','ETS',NULL,'ETS',NULL,NULL,NULL,'Lenel',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N/A',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'None Needed',NULL),
('Baker Systems Engineering','BE 437','Conference Room','ETS','ETS','CSE','8','2017*','Yes','Lenel','79','R3512','Behind TV','None',NULL,'15000',NULL,'4','0','Yes','TV',NULL,'TV','1','Webcam','1',NULL,'None Needed','Connected to Grad Office - place is a mess - room reeds re-evaluated'),
('Baker Systems Engineering','BE 441','Computer Lab',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Baker Systems Engineering','BE 442','Computer Lab',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Baker Systems Engineering','BE 443','Computer Lab',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Baker Systems Engineering','BE 444','Computer Lab',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Baker Systems Engineering','BE 470','Lab','ETS','Ohio Valley','CSE/ISE','85','2021',NULL,'Lenel','68','A109A3','Podium','Spectrum',NULL,'80000','81077.25','1','0','Yes','TV',NULL,'Crestron','6','Biamp','9',NULL,'Done',NULL),
('Baker Systems Engineering','BE 480','Lab','ETS','OTDI','CSE/ISE','40','2021',NULL,'Lenel','68','A109A3','In-Room','Spectrum',NULL,'Level 2','81077.25','3','0','Yes','Projector (2)',NULL,'Crestron','6','Shure MXA','1',NULL,'Done',NULL),
('Bevis Hall','BH 241','Conference Room','ETS','Ohio Valley','BME','12','2023','Yes','Swipe Access','0','BMC9','None','None',NULL,'15000','13451','2','0','Yes','TV',NULL,'Soundbar','1','Soundbar','1',NULL,'Done',NULL),
('Bevis Hall','BH 245','Classroom','ETS','Ohio Valley','BME','40','2023',NULL,'Swipe Access','0','BMD19','Podium','Spectrum',NULL,'Level 2','45935','2','0','Yes','Motorized Screen',NULL,'Crestron','6','Biamp','4',NULL,'Done',NULL),
('Bevis Hall','BH 249','Conference Room','ETS','Ohio Valley','BME','12','2023','Yes','Swipe Access','0','R7264','None','None',NULL,'15000','13451','2','0','Yes','TV',NULL,'Soundbar','1','Soundbar','1',NULL,'Done',NULL),
('Bevis Hall','BH 270D','Conference Room','ETS','ETS','BME','12','2022','No','Key','0','R7264','None','None',NULL,'15000',NULL,'2','0','Yes','TV',NULL,'Soundbar','1','Soundbar','1',NULL,'Done',NULL),
('Bevis Hall','BH 315A','Conference Room','ETS','ETS','SIMcenter','7','2023','No','Swipe','0','R9918X','Behind TV','None',NULL,'15000',NULL,'2','0','Yes','TV',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bevis Hall','BH 315K','Conference Room','ETS','ETS','SIMcenter','2','2023','No','Swipe','0','R9918X','Behind TV','None',NULL,'15000',NULL,'1','0','Yes','TV','None','SOundbar','1','Soundbar','1',NULL,'Needs once PC is installed',NULL),
('Bolz Hall','BO 102','Classroom','ETS','ETS','MAE',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Will need custom - currently not installed',NULL),
('Bolz Hall','BO 117D','Conference Room','ETS','ETS',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bolz Hall','BO 130','Lab','ETS',NULL,'CEGE',NULL,'2021',NULL,'Key','80','57AD38',NULL,NULL,NULL,'Level 2',NULL,NULL,NULL,'No',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bolz Hall','BO 330','Conference Room','ETS','Unknown','CEGE','12','2017*','Yes','Key','82','FAA1','Behind TV','None',NULL,'15000',NULL,'2','0','Yes','TVs',NULL,'TV','1','Panacast','1',NULL,'Needs Updated - old guide is in folder',NULL),
('Bolz Hall','BO 405','Teaching Lab','ETS','Ohio Valley','CEGE',NULL,'2019',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Level 3','130824',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bolz Hall','BO 410','Teaching Lab','ETS','Ohio Valley','CEGE','42','2021',NULL,'Lenel','80','G7A15','415M','Hudson',NULL,'Level 3','130824','2','1','No','TVs',NULL,'Crestron','12','Shure MXA','2',NULL,'Done',NULL),
('Bolz Hall','BO 415','Teaching Lab','ETS','Ohio Valley','CEGE','70','2021',NULL,'Lenel','80','NAC7','415M','Hudson',NULL,'Level 3','130824','1','0','No','None',NULL,'Crestron','16','None','0',NULL,'Needs Custom Touch Panel - need pics of panel',NULL),
('Bolz Hall','BO 420','Teaching Lab','ETS','Ohio Valley','CEGE','42','2021',NULL,'Lenel','24','J11D0018','415M','Hudson',NULL,'Level 3','130824','2','1','Yes','TVs',NULL,'Crestron','12','Shure MXA','2',NULL,'Done',NULL),
('Bolz Hall','BO 420A','Huddle Space','ETS','Ohio Valley','CEGE','6','2021',NULL,'Unlocked','None','None','Behind TV','None',NULL,'15000','0','2','0','Yes','TV',NULL,'Soundbar','1','Soundbar','1',NULL,'None Needed',NULL),
('Bolz Hall','BO 424','Huddle Space','ETS','Ohio Valley','CEGE','6','2021',NULL,'Unlocked','None','None','Behind TV','None',NULL,'15000',NULL,'2','0','Yes','TV',NULL,'Soundbar','1','Soundbar','1',NULL,'None Needed',NULL),
('Bolz Hall','BO 426','Conference Room','ETS','Ohio Valley','CEGE','10','2021','Yes','Unlocked','None','None','Behind TV','None',NULL,'15000',NULL,'2','0','Yes','TV',NULL,'Soundbar','1','Soundbar','1',NULL,'Done',NULL),
('Bolz Hall','BO 430A','Huddle Space','ETS','Ohio Valley','CEGE','5','2021',NULL,'Unlocked','None','None','Behind TV','None',NULL,'15000',NULL,'2','0','Yes','TV',NULL,'Soundbar','1','Soundbar','1',NULL,'None Needed',NULL),
('Bolz Hall','BO 430B','Huddle Space','ETS','Ohio Valley','CEGE','5','2021',NULL,'Unlocked','None','None','Behind TV','None',NULL,'15000',NULL,'2','0','Yes','TV',NULL,'Soundbar','1','Soundbar','1',NULL,'None Needed',NULL),
('Bolz Hall','BO 432','Conference Room','ETS','Ohio Valley','CEGE','6','2021','Yes','Unlocked','None','None','Behind TV','None',NULL,'15000',NULL,'2','0','Yes','TV',NULL,'Soundbar','1','Soundbar','1',NULL,'Done',NULL),
('CAR','CAR 100A','Office','CAR','Ohio Valley','CAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Level 1','0',NULL,NULL,'Yes',NULL,NULL,NULL,'0',NULL,'0',NULL,'None Needed',NULL),
('CAR','CAR 100B','Office','CAR','Ohio Valley','CAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('CAR','CAR 100C','Office','CAR','Ohio Valley','CAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'TV',NULL,NULL,NULL,NULL,NULL,NULL,'None Needed',NULL),
('CAR','CAR 120A',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('CAR','CAR 180','Computer Lab','PACE',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('CAR','CAR 198','Classroom','CAR','Ohio Valley','CAR','24','2021',NULL,'Key','71','GC6AA','Podium','On Podium',NULL,NULL,NULL,'2','1','Yes','Motorized Screen',NULL,'Crestron','6','Shure MXA','1',NULL,'Done',NULL),
('CAR','CAR 210','Conference Room','CAR','Ohio Valley','CAR','10','2021','Yes','Key','71','GC6AA1','Behind TV','None',NULL,'15000',NULL,'2','0','Yes','TV',NULL,'Soundbar','1','Soundbar','1',NULL,'Needs Custom remote - sony remote. 1 - PC, 2 - Air Media, 3 - Guest HDMI',NULL),
('CAR','CAR 227','Office','CAR','Ohio Valley','CAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('CAR','CAR Special Projects Building','Teaching Lab',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('CBEC','CB 016','Mixed Purpose','ETS',NULL,'CBE',NULL,'2013*',NULL,'Lenel','CBEC 1','X1B2',NULL,NULL,NULL,'150000',NULL,NULL,NULL,'Yes',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'None Needed',NULL),
('CBEC','CB 030','Computer Lab','No AV',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'None Needed',NULL),
('CBEC','CB 110','Lab','ETS','ETS','CBE','50','5+ Years Old',NULL,'Lenel','CBEC 1','X1B12','CB 145','None',NULL,'Level 2',NULL,'4','3','Yes','Motorized Screen',NULL,'Crestron','6','Old In-Ceiling','2',NULL,'None Needed','Combines with 120 - no video conference'),
('CBEC','CB 120','Lab','ETS','ETS','CBE','100','5+ Years Old',NULL,'Lenel','CBEC 1','X1B12','CB 145','None',NULL,'Level 2',NULL,'4','3','Yes','Motorized Screen',NULL,'Crestron','6','Old In-Ceiling','2',NULL,'Needs Custom - see pics','Combines with 110'),
('CBEC','CB 141','ETS Storage','ETS',NULL,'ETS',NULL,NULL,NULL,'Key','CBEC 1','X1B12',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'None Needed',NULL),
('CBEC','CB 151','Mixed Purpose','ETS',NULL,'CBE',NULL,'2013*',NULL,'Lenel','CBEC 1','X1B12',NULL,NULL,NULL,'150000',NULL,NULL,NULL,'Yes',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'None Needed','No Video Conference'),
('CBEC','CB 153','Mixed Purpose','ETS',NULL,'CBE',NULL,'2013*',NULL,'Lenel','CBEC 1','X1B12',NULL,NULL,NULL,'150000',NULL,NULL,NULL,'Yes',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'None Needed',NULL),
('CBEC','CB 169','Classroom','ETS','Ohio Valley','CBE','36','2023',NULL,'Lenel','CBEC 1','X1B2256','Podium','Spectrum',NULL,'Level 2',NULL,'5','3','Yes','Motorized Screen',NULL,'Crestron','4','Biamp','6',NULL,'Done',NULL),
('CBEC','CB 230','Conference Room','ETS','Ohio Valley','CBE','12','2022','Yes','Key','CBEC 1','X1A1X','In-Room','None',NULL,'30000',NULL,'2','1','Yes','TV',NULL,'Crestron','6','Biamp','3',NULL,'Done',NULL),
('CBEC','CB 267','Conference Room','Shared w/ ASC','Ohio Valley','CBE','12','2023','Yes','Key','CBEC 1','X1A1X','Podium','Spectrum',NULL,'50000',NULL,'2','0','Yes','Motorized Screen',NULL,'Crestron','4','Biamp','4',NULL,'Done',NULL),
('CBEC','CB 316','Conference Room','ETS','Ohio Valley','CBE','8','2020','Yes','Key','CBEC 1','X1A1X','Behind TV','None',NULL,'15000',NULL,'2','0','Yes','TV',NULL,'Soundbar','1','Soundbar','1',NULL,'Done',NULL),
('CBEC','CB 330','Conference Room','ETS','Ohio Valley','CBE','12','2022','Yes','Key','CBEC 1','X1A1X','In-Room','None',NULL,'30000',NULL,'2','0','Yes','TV',NULL,'Crestron','6','Biamp','3',NULL,'Done',NULL),
('CBEC','CB 430','Conference Room','ETS','Ohio Valley','ECE','12','2022','Yes','Key','CBEC 1','X1A1X','In-Room','None',NULL,'30000',NULL,'2','0','Yes','TV',NULL,'Crestron','6','Biamp','3',NULL,'Done',NULL),
('CBEC','CB 467','Conference Room','ETS','ETS','CBE','8','2015*','Yes','Key','CBEC 1','X1A1X','Behind TV','None',NULL,'15000',NULL,'2','0','Yes','TV',NULL,'Soundbar','1','Soundbar','1',NULL,'Done',NULL),
('CBEC','CB 468','Conference Room','ETS','ETS','CBE','8','2015*','Yes','Key','CBEC 1','X1A1X','Behind TV','None',NULL,'15000',NULL,'2','0','Yes','TV',NULL,'Soundbar','1','Soundbar','1',NULL,'Done',NULL),
('CBEC','CB 610','Student Lounge','ETS','ETS',NULL,'20','5+ Years Old',NULL,'Public','None','None','Under Table','None','None','Level 1',NULL,'N/A','0','No','TV',NULL,'TV','4','None','0',NULL,'None Needed',NULL),
('Caldwell Laboratory','CL 112','Computer Lab','No AV',NULL,'CSE','100',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'None Needed',NULL),
('Caldwell Laboratory','CL 112A','Computer Lab','ETS','ETS','CSE','50','2014*',NULL,'Key','3','G11B11','None','None','None','50000',NULL,'0','0','No','Projector',NULL,'None','0','None','0',NULL,'None Needed','Portable projector'),
('Caldwell Laboratory','CL 112B','ETS Storage','ETS',NULL,'ETS',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'None Needed',NULL),
('Caldwell Laboratory','CL 112D','Computer Lab','No AV',NULL,'CSE','20',NULL,NULL,NULL,'3','G11B11',NULL,NULL,NULL,'Level 1',NULL,NULL,NULL,'N/A',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'None Needed',NULL),
('Caldwell Laboratory','CL 214','Conference Room','ETS','ETS','ECE','8','2014*','Yes','Key','3','G11B11','None','None','None','15000',NULL,'0','0','No','Projector',NULL,'None','0','None','0',NULL,'None Needed',NULL),
('Caldwell Laboratory','CL 218','Computer Lab','ETS','ETS','CSE','15',NULL,NULL,NULL,'3','G11B11',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N/A',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'None Needed','Not functioning - no projector - see pics'),
('Caldwell Laboratory','CL 234','Teaching Lab','No AV',NULL,'CSE','20',NULL,NULL,NULL,'3','G11B11',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N/A',NULL,NULL,'N/A','0','N/A','0',NULL,'None Needed',NULL),
('Caldwell Laboratory','CL 237','Teaching Lab','ETS','ETS','CSE','40','2015*',NULL,'Lenel','3','G5A81','None','None','None','50000',NULL,'1','0','Yes','None',NULL,'Owl','1','Owl','1',NULL,'None Needed','Instrcutor has installed own sound system and TV - not ours to manage'),
('Caldwell Laboratory','CL 260','Computer Lab','No AV',NULL,'ECE',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0',NULL,'0',NULL,'None Needed',NULL),
('Caldwell Laboratory','CL 403','Conference Room','ETS','ETS','CSE','10','2023','Yes','Lenel','3','G70107','None','None','None','15000',NULL,'0','0','No','Projector',NULL,'None','0','None','0',NULL,'None Needed','Temporary'),
('CEMAS','CMAS 101','Conference Room','Department',NULL,'CEMAS',NULL,'2023*','Yes','Key',NULL,NULL,NULL,NULL,NULL,'15000',NULL,NULL,NULL,'No',NULL,NULL,NULL,'0',NULL,'0',NULL,'None Needed',NULL),
('CEMAS','CMAS 103','Office','Department',NULL,'CEMAS',NULL,NULL,NULL,'Key',NULL,NULL,NULL,NULL,NULL,NULL,'0',NULL,NULL,'No',NULL,NULL,NULL,'0',NULL,'0',NULL,'None Needed',NULL),
('CEMAS','Digital Theater','Classroom','Department',NULL,'CEMAS',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'No',NULL,NULL,NULL,'0',NULL,'0',NULL,'None Needed',NULL),
('Dreese Laboratories','DL 046','ETS Storage','ETS',NULL,'ETS',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'None Needed',NULL),
('Dreese Laboratories','DL 172','Computer Lab','No AV',NULL,'CSE',NULL,NULL,NULL,NULL,'3',NULL,NULL,NULL,NULL,'Level 2',NULL,NULL,NULL,'N/A',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'None Needed',NULL),
('Dreese Laboratories','DL 259','Conference Room','ETS','Ohio Valley','ECE','16','2023','Yes','Key','3','G8AA4','Behind TV','None',NULL,'15000',NULL,'2','0','Yes','TV',NULL,'Soundbar','1','Soundbar','1',NULL,'Done',NULL),
('Dreese Laboratories','DL 260','Conference Room','ETS','Ohio Valley','ECE','50','2021','Yes','Key','3','G8AA 2','In-Podium','Unlocked',NULL,'50000',NULL,'4','2','Yes','Pull Down Screens',NULL,'Crestron','4','Biamp','4',NULL,'Done',NULL),
('Dreese Laboratories','DL 263','Conference Room','ETS','New Era','CSE','16','2018','Yes','Swipe Access','0','G7A 21','Podium','Spectrum',NULL,'50000',NULL,'2','1','Yes','TV',NULL,'Atlas','2','Wireless Tabletop','8',NULL,'Done',NULL),
('Dreese Laboratories','DL 267','Conference Room','ETS','ETS','CSE','16','2022','Yes','Key','3','68AA 4','Behind TV','None',NULL,'15000',NULL,'2','1','Yes','TV',NULL,'Soundbar','1','Soundbar','1',NULL,'Done',NULL),
('Dreese Laboratories','DL 280','Teaching Lab','ETS','Ohio Valley','CSE','50','2021',NULL,'Swipe Access','3','G795','Credenza','Screwdriver',NULL,'Level 2',NULL,'2','1','Yes','Motorized Screen',NULL,'Crestron','4','Biamp','2',NULL,'Done',NULL),
('Dreese Laboratories','DL 298','Conference Room','ETS','ETS','ECE','12','2015','Yes','Key','4','G7A15','None','Spectrum',NULL,'15000',NULL,'2','1','Yes','TV',NULL,'TV','1','Vaddio','2',NULL,'Done',NULL),
('Dreese Laboratories','DL 395N','Office','ETS','Check in on a Monday','CSE',NULL,'5+ Years Old',NULL,NULL,'3','1XG7A',NULL,NULL,NULL,'Level 1',NULL,NULL,NULL,'Yes',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'None Needed',NULL),
('Dreese Laboratories','DL 395S','Conference Room','ETS','ETS','CSE','10','2023','No','None','None','None','Behind TV','None','None','15000',NULL,'2','0','Yes','TV',NULL,'Soundbar','1','Soundbar','1',NULL,'Done',NULL),
('Dreese Laboratories','DL 405',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Dreese Laboratories','DL 480','Lab','ETS','Ohio Valley','CSE','50','2021',NULL,'Swipe Access','3','G796','Credenza','None',NULL,'Level 2',NULL,'2','1','Yes','Motorized Screen',NULL,'Crestron','4','Biamp','2',NULL,'Done',NULL),
('Dreese Laboratories','DL 517','Computer Lab','No AV',NULL,'ECE',NULL,NULL,NULL,'Swipe Access','3','G5C-5',NULL,NULL,NULL,'Level 2',NULL,NULL,NULL,'N/A',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'None Needed',NULL),
('Dreese Laboratories','DL 531','ETS Storage','ETS',NULL,'ETS',NULL,NULL,NULL,'Swipe Access','3','R71BB4',NULL,NULL,NULL,'Level 2',NULL,NULL,NULL,'N/A',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'None Needed',NULL),
('Dreese Laboratories','DL 557','Computer Lab','No AV',NULL,'ECE',NULL,NULL,NULL,'Swipe Access','3','G5C-5',NULL,NULL,NULL,'Level 2',NULL,NULL,NULL,'N/A',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'None Needed',NULL),
('Dreese Laboratories','DL 569','Computer Lab','No AV',NULL,'ECE',NULL,NULL,NULL,'Swipe Access','3','G5A-21',NULL,NULL,NULL,'Level 2',NULL,NULL,NULL,'N/A',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'None Needed',NULL),
('Dreese Laboratories','DL 698','Conference Room','ETS','ETS','CSE','12','2015*','Yes','Key','4','G7A15','None','Spectrum',NULL,'15000',NULL,'2','1','Yes','TV',NULL,'TV','1','Vaddio','2','Needed','Done',NULL),
('Dreese Laboratories','DL 761','Computer Lab','No AV',NULL,'ECE',NULL,NULL,NULL,'Swipe Access','3','G8B0127',NULL,NULL,NULL,'Level 2',NULL,NULL,NULL,'N/A',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'None Needed',NULL),
('Dreese Laboratories','DL 808','Conference Room','ETS','ETS','ECE','8','2023','Yes','Swipe Access','3','N/A','behind TV','None',NULL,'15000',NULL,'2','0','No','TV',NULL,'TV','1','None','0','Needed','None Needed',NULL),
('Dreese Laboratories','DL 817','Computer Lab','No AV',NULL,'ECE',NULL,NULL,NULL,'Swipe Access','3','G5C-5',NULL,NULL,NULL,'Level 2',NULL,NULL,NULL,'N/A',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'None Needed',NULL),
('Edison Joining Technology Center','ED 102','Conference Room','ETS','ETS','WE','10','2015*','Yes','Key','0','AA','Behind TV','None',NULL,'15000',NULL,'2','0','Yes',NULL,NULL,'Soundbar','1','Soundbar','1',NULL,'Needs custom - revisit room',NULL),
('Edison Joining Technology Center','ED 105','Mixed Purpose','ETS','ETS','WE','24','2014*',NULL,'Key','0',NULL,'Behind TV','None',NULL,'50000',NULL,'2','0','No',NULL,NULL,'None','0','None','0',NULL,'Needs custom - revisit room','Projector turns on via switch by PC'),
('Edison Joining Technology Center','ED 111','Classroom','ETS','ETS','WE','70','5+ Years Old',NULL,'Key','0','AM','In-Room','None',NULL,'Level 1',NULL,NULL,NULL,'Yes',NULL,NULL,'None','0','MXL','1',NULL,'Needs custom - revisit room',NULL),
('Electroscience Laboratory - New','ESL 132','Conference Room','ETS','Live Technology','ESL','40','2017*','Yes','Key','0',NULL,'In-Room','Unlocked',NULL,'50000',NULL,'1','0','Yes','TV',NULL,'EV','4','ClearOne','49051',NULL,'Needs custom - revisit room','Old touch panel design'),
('Electroscience Laboratory - New','ESL 141','Conference Room','ETS','Ohio Valley','ESL','8','2017*','Yes','None','0','N/A','Behind TV','None',NULL,'15000',NULL,NULL,NULL,'Yes','TV',NULL,'TV','1','HuddleCam','1',NULL,NULL,NULL),
('Electroscience Laboratory - New','ESL 150A','Conference Room','ETS','ETS','ESL','8','2017*','No','Key','0','BEST','Behind TV','None',NULL,'15000',NULL,'2','1','No','TV',NULL,'TV','1','None','0',NULL,'Needs custom - revisit room',NULL),
('Electroscience Laboratory - Old','ESL 238','Conference Room','ETS','ETS','ESL','12','2017*','Yes','Key','Open','None','TV','None',NULL,'15000',NULL,'0','0','No','TV',NULL,'TV','1','None','0',NULL,'Needs custom - revisit room',NULL),
('Electroscience Laboratory - Old','ESL 240','Conference Room','ETS','ETS','ESL','12','2017*','Yes','Key','Open','None','TV','None',NULL,'15000',NULL,'0','0','No','TV',NULL,'TV','1','None','0',NULL,'Needs custom - revisit room',NULL),
('Fontana Laboratories','FL 0125','Huddle Space','ETS','Soundcom','MSE','6','2020',NULL,'Lenel','0',NULL,'Behind TV','None',NULL,'Level 1',NULL,'1','0','No','TV',NULL,'TV','1','None','0',NULL,'None Needed','Button panel no power - see notes'),
('Fontana Laboratories','FL 0145','Computer Lab','ETS',NULL,NULL,NULL,'2020',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'80000',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Fontana Laboratories','FL 0152','Classroom','ETS','Soundcom','MSE','12','2020',NULL,'Lenel','0','A52A-5','In-Room','Middle Atlantic',NULL,'Level 2',NULL,'0','0','No','TV',NULL,'TV','1','None','0',NULL,'None Needed',NULL),
('Fontana Laboratories','FL 1110','Teaching Lab','ETS','Soundcom','BME','16','2020',NULL,'Lenel','0','A52A-5','In-Room','Loose',NULL,'Level 1',NULL,NULL,NULL,'Yes',NULL,NULL,'None','0','None','0',NULL,'None Needed',NULL),
('Fontana Laboratories','FL 1120','Teaching Lab','ETS','Soundcom','BME','10','2020',NULL,'Lenel','0','A52A-5','None','None',NULL,'Level 1',NULL,'2','1','No','Projector',NULL,'None','0','None','0',NULL,'None Needed',NULL),
('Fontana Laboratories','FL 1124','Teaching Lab','ETS','Soundcom','BME','18','2020',NULL,'Lenel','0','A52A-5','In Cabinate','None',NULL,'Level 1',NULL,NULL,NULL,'No','Projector',NULL,'JBL','6','None','0',NULL,'None Needed',NULL),
('Fontana Laboratories','FL 1125','Mixed Purpose','ETS','Soundcom','BME','21','2020',NULL,'Lenel','0','A52A-5','In-Room','Middle Atlantic',NULL,'Level 2',NULL,'2','0','Yes','Projector',NULL,'JBL','12','None','0',NULL,'Done',NULL),
('Fontana Laboratories','FL 1135','Teaching Lab','ETS','Soundcom','MSE','30','2020',NULL,'Lenel','0','A52A-5','In-Room','Middle Atalantic',NULL,'Level 2',NULL,'1','0','No','TV',NULL,'None','0','None','0',NULL,'None Needed',NULL),
('Fontana Laboratories','FL 1136','Teaching Lab',NULL,NULL,'BME',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Fontana Laboratories','FL 1155','Lab','ETS','Soundcom','MAE','20','2020',NULL,'Lenel',NULL,NULL,'Behind TV','None',NULL,'Level 1',NULL,'0','0','No','TV',NULL,'TV','1','None','0',NULL,'None Needed',NULL),
('Fontana Laboratories','FL 2000','Conference Room','ETS','Soundcom','MAE','40','2020','Yes','Lenel','0','A52A-5','In-Room','Middle Atlantic',NULL,'50000',NULL,'N/A','0','Yes','Interactive Projectors',NULL,'JBL','12','Shure MXA','2',NULL,'Done',NULL),
('Fontana Laboratories','FL 2118','Conference Room','ETS','Soundcom','MAE','10','2020','Yes','Swipe Access','0',NULL,'In-Room','Middle Atlantic',NULL,'30000',NULL,NULL,NULL,'Yes',NULL,NULL,'JBL','2','Shure MXA','1',NULL,'Done',NULL),
('Fontana Laboratories','FL 2119','Huddle Space','ETS','Soundcom','MAE','4','2020',NULL,'Public','None','R67D01','Behind TV','None',NULL,'Level 1',NULL,'2','1','No','TV',NULL,'TV','1','None','0',NULL,'None Needed',NULL),
('Fontana Laboratories','FL 2124A','Conference Room','ETS','Soundcom','BME','6','2020','No','Swipe Access','0','N/A','Behind TV','None',NULL,'15000',NULL,'2','0','No','TV',NULL,'TV','1','None','0',NULL,'Done',NULL),
('Fontana Laboratories','FL 2125/35','Mixed Purpose','ETS','Soundcom','MSE','84','2020',NULL,'Lenel','0','A52A-6','In-Room','Middle Atlantic',NULL,'100000',NULL,NULL,NULL,'Yes',NULL,NULL,'JBL','24','Podium','6',NULL,'Done','Touch Screens need to be powered on for PC to display on projectors / Left Display 2125 controls in-room audio'),
('Fontana Laboratories','FL 2126','Conference Room','ETS','Soundcom','MAE','6','2020','Yes','Swipe Access','0',NULL,'Behind TV','Loose',NULL,'30000',NULL,NULL,NULL,'No',NULL,NULL,'None','0','None','0',NULL,'Done',NULL),
('Fontana Laboratories','FL 2130','Conference Room','ETS','Soundcom','MAE','12','2020','Yes','Swipe Access','0',NULL,'In-Room','Middle Atlantic',NULL,'30000',NULL,NULL,NULL,'Yes',NULL,NULL,'JBL','2','Shure MXA','1',NULL,'Done',NULL),
('Fontana Laboratories','FL 2136A','Conference Room','ETS','Soundcom','MSE','6','2020','No','Swipe Access','0','N/A','Behind TV','None',NULL,'15000',NULL,'2','0','No','TV',NULL,'TV','1','None','0',NULL,'Done',NULL),
('Fontana Laboratories','FL 3003','Huddle Space','ETS','Soundcom','MAE','4','2020',NULL,'Pulic','None','None','Behind TV','None',NULL,'Level 1',NULL,'2','1','No','TV',NULL,'TV','1','None','0',NULL,'None Needed',NULL),
('Fontana Laboratories','FL 3021','Conference Room','ETS','Soundcom','MAE','12','2020','Yes','Key','Office Desk','N/A','In-Room','Middle Atlantic',NULL,'30000',NULL,'0','0','Yes','TV',NULL,'JBL','2','Shure MXA','1',NULL,'Done',NULL),
('Fontana Laboratories','FL 3030','Huddle Space','ETS','Soundcom','MAE','6','2020',NULL,'Public','None','None','Behind TV','None',NULL,'Level 1',NULL,'2','1','No','TV',NULL,'TV','1','None','0',NULL,'None Needed',NULL),
('Fontana Laboratories','FL 3119','Huddle Space','ETS','Soundcom','MAE','4','2020',NULL,'Public','None','R67D01','Behind TV','None',NULL,'Level 1',NULL,'2','1','No','TV',NULL,'TV','1','None','0',NULL,'None Needed',NULL),
('Fontana Laboratories','FL 3124','Huddle Space','ETS','Soundcom','MAE','4','2020',NULL,'Swipe Access','0','None','Behind TV','None',NULL,'Level 1',NULL,'2','1','No','TV',NULL,'TV','1','None','0',NULL,'None Needed',NULL),
('Fontana Laboratories','FL 3144','Huddle Space','ETS','Soundcom','MAE','8','2020',NULL,'Swipe Access','0','None','Behind TV','None',NULL,'Level 1',NULL,'2','1','No','TV',NULL,'TV','1','None','0',NULL,'None Needed',NULL),
('Fontana Laboratories','FL 4003','Huddle Space','ETS','Soundcom','MAE','4','2020',NULL,'Pulic','None','None','Behind TV','None',NULL,'Level 1',NULL,'2','1','No','TV',NULL,'TV','1','None','0',NULL,'None Needed',NULL),
('Fontana Laboratories','FL 4021','Conference Room','ETS','Soundcom','MAE','12','2020','Yes','Key','Office Desk','N/A','In-Room','Middle Atlantic',NULL,'30000',NULL,'0','0','Yes','TV',NULL,'JBL','2','Shure MXA','1',NULL,'Done',NULL),
('Fontana Laboratories','FL 4030','Huddle Space','ETS','Soundcom','MAE','0','2020',NULL,'Swipe Access',NULL,NULL,'Behind TVs','None',NULL,'Level 1',NULL,'2','1','No','TV',NULL,'TV','1','None','0',NULL,'None Needed',NULL),
('Fontana Laboratories','FL 4119','Huddle Space','ETS','Soundcom','MAE','4','2020',NULL,'Public','None','R67D01','Behind TV','None',NULL,'Level 1',NULL,'2','1','No','TV',NULL,'TV','1','None','0',NULL,'None Needed',NULL),
('Fontana Laboratories','FL 4124','Huddle Space','ETS','Soundcom','MAE','4','2020',NULL,'Swipe Access','0','None','Behind TV','None',NULL,'Level 1',NULL,'2','1','No','TV',NULL,'TV','1','None','0',NULL,'None Needed',NULL),
('Fontana Laboratories','FL 4144','Huddle Space','ETS','Soundcom','MAE','8','2020',NULL,'Swipe Access','0','N/A','Behind TV','None',NULL,'Level 1',NULL,'2','1','No','TV',NULL,'TV','1','None','0',NULL,'None Needed',NULL),
('Hitchcock Hall','HI 155','Conference Room','ETS','New Era','Administration','14','2017','Yes','Open',NULL,NULL,'Cabinet','N/A',NULL,'50000',NULL,'5','1','Yes',NULL,NULL,'Atlas','3','ClearOne','2',NULL,'Not Needed - will be getting upgraded',NULL),
('Hitchcock Hall','HI 206','Teaching Lab','ETS','Ohio Valley','EED','36','2021',NULL,'Lenel','KEY TRIGGERS ALARM','A24A5','Podium','Hudson',NULL,'Level 2',NULL,'2','0','Yes','Projector/TV',NULL,'JBL','8','Biamp','3',NULL,'Done',NULL),
('Hitchcock Hall','HI 208','Teaching Lab','ETS','Ohio Valley','EED','24','2020',NULL,'Lenel','KEY TRIGGERS ALARM','A24A5','Podium','Spectrum',NULL,'Level 2',NULL,'2','0','Yes','TV',NULL,'JBL','4','Biamp','3',NULL,'Done','No projector - mount and cables in place'),
('Hitchcock Hall','HI 214','Teaching Lab','ETS','Ohio Valley','EED','36','2021',NULL,'Lenel','KEY TRIGGERS ALARM','A24A5','Podium','Spectrum',NULL,'Level 2',NULL,'2','0','Yes','Projector/TV',NULL,'JBL','10','Biamp','3',NULL,'Done',NULL),
('Hitchcock Hall','HI 216','Teaching Lab','ETS','Ohio Valley','EED','36','2022',NULL,'Lenel','KEY TRIGGERS ALARM','A24A5','Podium','Spectrum',NULL,'Level 2',NULL,'2','0','Yes','Projector/TV',NULL,'JBL','8','Biamp','3',NULL,'Done',NULL),
('Hitchcock Hall','HI 224','Teaching Lab','ETS','Ohio Valley','EED','72','2020',NULL,'Lenel','KEY TRIGGERS ALARM','A24A5','Podium','Hudson',NULL,'Level 3',NULL,'2','0','Yes','Projector/TV',NULL,'JBL','20','Biamp','6',NULL,'Done',NULL),
('Hitchcock Hall','HI 244G','Conference Room','ETS','ETS','ETS','10','2023','No','Swipe','None','None','Behind TV','None',NULL,'15000',NULL,'1','o','Yes','TV',NULL,'Soundbar','1','Soundbar','1',NULL,'Needs custom - revisit room',NULL),
('Hitchcock Hall','HI 302','ETS Storage','ETS',NULL,'ETS',NULL,NULL,NULL,'Lenel',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'None Needed',NULL),
('Hitchcock Hall','HI 308','Teaching Lab','ETS','Ohio Valley','EED','72','2020',NULL,'Lenel','KEY TRIGGERS ALARM','A24A5','Podium','Spectrum',NULL,'Level 3',NULL,'3','1','Yes','Projector/TV',NULL,'JBL','20','Biamp','6',NULL,'Done',NULL),
('Hitchcock Hall','HI 316','Computer Lab','No AV',NULL,'EED',NULL,NULL,NULL,'Lenel','0',NULL,NULL,NULL,NULL,'Level 1',NULL,NULL,NULL,'N/A',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'None Needed',NULL),
('Hitchcock Hall','HI 346','Teaching Lab','ETS','Ohio Valley','EED','36','2022',NULL,'Lenel','KEY TRIGGERS ALARM','A24A5','Podium','Spectrum',NULL,'Level 2',NULL,'2','0','Yes','Projector/TV',NULL,'JBL','8','Biamp','3',NULL,'Done',NULL),
('Hitchcock Hall','HI 349','ETS Storage','ETS',NULL,'ETS',NULL,NULL,NULL,'Swipe',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'None Needed',NULL),
('Hitchcock Hall','HI 410','Conference Room','ETS','Ohio Valley','CEGE','16','2021','Yes','Key','145','9A16','Podium','Spectrum',NULL,'50000',NULL,'4','2','Yes','Motorized Screen',NULL,'Crestron','6','Biamp','4',NULL,'Needs standard touch - need Zoom drivers',NULL),
('Hitchcock Hall','HI 416','Conference Room','ETS','Ohio Valley','CEGE','16','2020*','Yes','Key','Key in 470','9A16','Behind TV','None',NULL,'15000',NULL,'2','0','Yes','TV',NULL,'Soundbar','0','Soundbar','0',NULL,'Needs standard Button - see pics',NULL),
('Hitchcock Hall','HI 418','Lab','ETS','Unknown','CEGE','12','Unknown',NULL,'Key','Key in 470','9A54','In-Room','None',NULL,'Level 1',NULL,'2','2','No','Motorized Screen',NULL,'None','0','None','0',NULL,'None Needed',NULL),
('Hitchcock Hall','HI 426','Conference Room','ETS','Unknown','CEGE','16','2024','Yes','Key','145','9A28','None','None',NULL,'30000',NULL,'1','0','No','Pull Down Screen',NULL,'JBL','4','None','0',NULL,'Needs button panel - see pics',NULL),
('Hitchcock Hall','HI 446','Classroom','ETS',NULL,'CEGE',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Hitchcock Hall','HI 495','Office Suite',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Needs condensed air media',NULL),
('Knowlton Hall','KN 100B','Huddle Space','ETS','ETS','KSA','25',NULL,NULL,'Unlocked','None','None','Behind TV','None',NULL,'Level 1',NULL,'3','3','No','TV',NULL,'TV','1','None','0',NULL,'Done',NULL),
('Knowlton Hall','KN 175','Classroom','ETS','Ohio Valley','KSA','40','2019',NULL,'Key','8','G88A256X','Podium','CompX C413A',NULL,'50000',NULL,'2','0','Yes','Motorized Screen',NULL,'Crestron','6','Podium','1',NULL,'Done',NULL),
('Knowlton Hall','KN 176','Classroom','ETS','Ohio Valley','KSA','30','2019',NULL,'Key','8','G88A256X','Podium','CompX C413A',NULL,'50000',NULL,'2','0','Yes','Motorized Screen',NULL,'Crestron','4','Podium','1',NULL,'Done',NULL),
('Knowlton Hall','KN 177','Classroom','ETS','Ohio Valley','KSA','30','2019',NULL,'Key','8','G88A256X','Podium','CompX C413A',NULL,'50000',NULL,'2','0','Yes','Motorized Screen',NULL,'Crestron','4','Pdoium','1',NULL,'Done',NULL),
('Knowlton Hall','KN 200B','Conference Room','ETS','Radiant','KSA','16','2017*','No','Unlocked','None','None','In-Room','Middle Atlantic',NULL,'50000',NULL,'2','1','Yes','Motorized Screen',NULL,'Crestron','2','Meeting Owl','1',NULL,'Done',NULL),
('Knowlton Hall','KN 258','Classroom','ETS','Ohio Valley','KSA','16','45292',NULL,'Key','8','G88A256X','Podium','Middle Atlantic',NULL,'Level 1',NULL,'3','2','Yes','Pull Down Screen',NULL,'Crestron','2','Ceiling','2',NULL,'Done',NULL),
('Knowlton Hall','KN 259','Classroom','ETS','Ohio Valley','KSA','16','45292',NULL,'Key','8','G88A256X','Podium','Middle Atlantic',NULL,'Level 1',NULL,'3','2','Yes','Pull Down Screen',NULL,'Crestron','2','Ceiling','2',NULL,'Done',NULL),
('Knowlton Hall','KN 269','Classroom','ETS','Ohio Valley','KSA','14','2017*',NULL,'Key','8','G188A256X','Podium','Hudson',NULL,'50000',NULL,'3','2','No','Pull Down Screen',NULL,'Crestron','2','None','0',NULL,'Done',NULL),
('Knowlton Hall','KN 430','Mixed Purpose','ETS','OTDI','KSA','40','2022',NULL,'Swipe','15','G88E16X','Podium','CompX C413A',NULL,'Level 2',NULL,'6','4','Yes','Mounted Screens',NULL,'Anker','2','Shure MXA','1',NULL,'Done',NULL),
('Knowlton Hall','KN 430A','ETS Storage','ETS',NULL,'KSA',NULL,NULL,NULL,'Swipe',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Knowlton Hall','KN 448','Computer Lab','ETS',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Knowlton Hall','KN 450A','Conference Room','ETS','Ohio Valley','KSA','10','2019*','No','Unlocked','None','None','In-Room','Middle Atlantic',NULL,'15000',NULL,'3','2','No','TV',NULL,'TV','1','None','0',NULL,'None Needed',NULL),
('Knowlton Hall','KN 475','ETS Storage','ETS',NULL,'ETS',NULL,NULL,NULL,'Swipe',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'None Needed',NULL),
('Knowlton Executive Terminal','KT 210','Conference Room','ETS','New Era','Airport','12','2018','No','Key','67','DS3-1X','Credenza','None',NULL,'50000',NULL,'4','2','Yes','TV',NULL,'JBL','4','ClearOne','2',NULL,'Done',NULL),
('Knowlton Executive Terminal','KT 235','Classroom','ETS','Ohio Valley','Airport','40','2022',NULL,'Key','67','DS2-30','255','Middle Atlantic',NULL,'15000',NULL,'2','0','Yes','Motorized Screen',NULL,'Crestron','4','Biamp','6',NULL,'Done',NULL),
('Knowlton Executive Terminal','KT 245','Classroom','ETS','Ohio Valley','Airport','40','2022',NULL,'Key','67','DS2-30','255','Middle Atlantic',NULL,'Level 2',NULL,'2','0','Yes','Motorized Screen',NULL,'Crestron','4','Biamp','6',NULL,'Done',NULL),
('Knowlton Executive Terminal','KT 255','Classroom','ETS','Ohio Valley','Airport','40','2022',NULL,'Key','67','DS2-30','Back of Room','Middle Atlantic',NULL,'Level 2',NULL,'2','0','Yes','Motorized  Screen',NULL,'Crestron','4','Biamp','6',NULL,'Done',NULL),
('Knowlton Executive Terminal','KT 275','Conference Room','ETS','New Era','Airport','6','2019','Yes','Key','67','DS1-1X','None','None',NULL,'15000',NULL,'0','0','No','TV',NULL,'None','0','None','0',NULL,'None Needed',NULL),
('Pomerane Hall','PO 151','Computer Lab','No AV',NULL,'CSE',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N/A',NULL,NULL,NULL,'0',NULL,'0',NULL,'None Needed',NULL),
('Pomerene Hall','PO 155','Teaching Lab','ETS','iVideo','CSE','36','2017',NULL,'Swipe Access','0','R44-51','Podium','Spectrum',NULL,'Level 1',NULL,NULL,NULL,'Yes',NULL,NULL,'Crestron','6','Biamp','2',NULL,'Done',NULL),
('Pomerene Hall','PO 161','Classroom','ETS','iVideo','CSE','36','2017',NULL,'Swipe Access','0','R44-51','Podium','Spectrum',NULL,'Level 1',NULL,NULL,NULL,'Yes',NULL,NULL,'Crestron','6','Biamp','2',NULL,'Done',NULL),
('Smith Laboratory','SM 0094','Computer Lab','ETS',NULL,'EED',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Smith Laboratory','SM 0098','Computer Lab','ETS',NULL,'EED',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Smith Laboratory','SM 0106','Lab','ETS',NULL,'EED',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Smith Laboratory','SM 0190','ETS Storage','ETS',NULL,'ETS',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'None Needed',NULL),
('Smith Laboratory','SM 0194','ETS Storage','ETS',NULL,'ETS',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'None Needed',NULL),
('Smith Laboratory','SM 3011','Classroom','ETS','Ohio Valley','EED','16',NULL,NULL,'Swipe Access','0','X8B-9','Inside Dirt Wall','None',NULL,'Level 1',NULL,'0','0','Yes','Dirt Wall TV',NULL,'Soundbar','1','Soundbar','1',NULL,'Needs custom - see pics','Dirt Wall'),
('Smith Laboratory','SM 3042B','Office','ETS','ETS','EED','1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Smith Laboratory','SM 3058','Conference Room','ETS','ETS','EED','4','2023','Yes','Unlocked',NULL,NULL,NULL,NULL,NULL,'15000',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0',NULL,'0',NULL,'None Needed',NULL),
('Smith Laboratory','SM 3095','Conference Room','ETS','ETS','EED','12','2023','Yes','Unlocked','0','N/A','Behind TV','None',NULL,'15000',NULL,'2','0','Yes','TV',NULL,'Soundbar','1','Soundbar','1',NULL,'Done',NULL),
('Smith Laboratory','SM 3101','Classroom','ETS','Ohio Valley','EED','36',NULL,NULL,'Swipe Access','0','X8B-10','Inside Dirt Wall','None',NULL,'Level 1',NULL,'0','0','Yes','Dirt Wall TV',NULL,'Soundbar','1','Soundbar','1',NULL,'Needs custom - see pics','Dirt Wall'),
('Smith Laboratory','SM 5055','Conference Room','ETS','ETS',NULL,NULL,NULL,'Yes',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Scott Lab','SO E100','Classroom','ETS','Ohio Valley','MAE','70','2022',NULL,'Key','74','FAA-2','In-Room','Spectrum',NULL,'Level 2',NULL,'3','1','Yes','Motorized Screen',NULL,'Crestron','8','Shure MXA','2',NULL,'Done',NULL),
('Scott Lab','SO E141','Classroom','ETS','Radiant','CAR','36',NULL,NULL,'Key','74','FAA-2','Podium','Allen Key',NULL,'Level 2',NULL,'2','0','Yes','Projector',NULL,'Atlas - Wall','2','USB','1',NULL,'Needs Custom ','System sucks - See One Note Issues'),
('Scott Lab','SO E200','Mixed Purpose','ETS',NULL,'MAE',NULL,NULL,NULL,NULL,'74','FAD-4X',NULL,NULL,NULL,'Level 1',NULL,NULL,NULL,'No',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Needs custom - see pics',NULL),
('Scott Lab','SO E202','ETS Storage','ETS',NULL,'MAE',NULL,NULL,NULL,'Swipe',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'None Needed',NULL),
('Scott Lab','SO E203','Computer Lab','No AV',NULL,'MAE',NULL,NULL,NULL,NULL,'74','FAD-4X',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N/A',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'None Needed',NULL),
('Scott Lab','SO E205','Mixed Purpose','ETS','ETS','MAE','20','2013*',NULL,'Key','74','FAD-4X','None','None',NULL,'50000',NULL,'2','1','Yes','Projector',NULL,'None','0','MXL','1',NULL,'Needs custom - dual remotes - see pics',NULL),
('Scott Lab','SO E215','Computer Lab','ETS',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Scott Lab','SO E225','Computer Lab','No AV',NULL,'MAE',NULL,NULL,NULL,NULL,'74','FAD-4X',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N/A',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'None Needed',NULL),
('Scott Lab','SO E231','ETS Storage','ETS',NULL,'ETS',NULL,NULL,NULL,'Swipe',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'None Needed',NULL),
('Scott Lab','SO E238','Conference Room','ETS','ETS','MAE','10','2019','Yes','Key','74','FAA-3','None','None',NULL,'15000',NULL,'4','0','Yes','Projector',NULL,'Soundbar','1','Soundbar','1',NULL,'Needs custom - projector remote, plug in usb for soundbar',NULL),
('Scott Lab','SO E339','Conference Room','ETS','ETS','MAE','8','2024','Yes','Key','74','FAA-3','None','None',NULL,'15000',NULL,'2','2','No','Projector',NULL,'None','0','None','0',NULL,'Needs custom - L610 remote - Air media w/ autoswitch to hdmi on table',NULL),
('Scott Lab','SO E435','Conference Room','ETS','ETS','MAE','8','2024','Yes','Key','74','FAA-3','None','None',NULL,'15000',NULL,'2','2','No','Projector',NULL,'None','0','None','0',NULL,'None Needed',NULL),
('Scott Lab','SO E439','Conference Room','ETS','ETS','MAE','8','2024','Yes','Key','74','FAA-3','None','None',NULL,'15000',NULL,'2','2','No','Projector',NULL,'None','0','None','0',NULL,'Needs custom - revisit room','Upgrade list'),
('Scott Lab','SO E521/539','Grad Office','No AV',NULL,'MAE','20',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'None Needed',NULL),
('Scott Lab','SO E525','Conference Room','ETS','Ohio Valley','MAE','20','2018','Yes','Key','74','FAA-3','Podium','Unlocked',NULL,'50000',NULL,'6','5','Yes','Motorized Screen',NULL,'Crestron','4','Shure MXA','1',NULL,'Really Old Touch Panel (Blue Bckground) - need zoom drivers - same as ARC 100',NULL),
('Scott Lab','SO N146','Computer Lab','No AV',NULL,'MAE',NULL,NULL,NULL,NULL,'74','FAA-3',NULL,NULL,NULL,'Level 1',NULL,NULL,NULL,'N/A',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'None Needed',NULL),
('Scott Lab','SO N148','Computer Lab','No AV',NULL,'MAE',NULL,NULL,NULL,NULL,'74','FAA-3',NULL,NULL,NULL,'Level 1',NULL,NULL,NULL,'N/A',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'None Needed',NULL),
('Scott Lab','SO N151','Computer Lab','No AV',NULL,'MAE',NULL,NULL,NULL,NULL,'74','FAD-4X',NULL,NULL,NULL,'Level 1',NULL,NULL,NULL,'N/A',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'None Needed',NULL),
('Scott Lab','SO N152','Computer Lab','No AV',NULL,'MAE',NULL,NULL,NULL,NULL,'74','FAA-3',NULL,NULL,NULL,'Level 1',NULL,NULL,NULL,'N/A',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'None Needed',NULL),
('Scott Lab','SO N154','Computer Lab','No AV',NULL,'MAE',NULL,NULL,NULL,NULL,'74','FAA-3',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N/A',NULL,NULL,NULL,'0',NULL,'0',NULL,'None Needed',NULL),
('Scott Lab','SO N156','Computer Lab','No AV',NULL,'MAE',NULL,NULL,NULL,NULL,'74','FAA-3',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N/A',NULL,NULL,NULL,'0',NULL,'0',NULL,'None Needed',NULL),
('Scott Lab','SO N250A','Conference Room','ETS','ETS','MAE','8','2023','No','Key','74','FAA-3','Behind TV','None',NULL,'15000',NULL,'2','0','Yes','TV',NULL,'TV','1','Webcam','1',NULL,'None Needed',NULL),
('Scott Lab','SO N350A','Conference Room','ETS','ETS','MAE','8','2023','No','Key','74','FAA-3','Behind TV','None',NULL,'15000',NULL,'2','0','Yes','TV',NULL,'TV','1','Webcam','1',NULL,'None Needed',NULL),
('Scott Lab','SO N350C','Office','MAE','Ohio Valley','MAE','4',NULL,NULL,'Key','74','FAA-3','Behind TV','None',NULL,'Level 1',NULL,'2','0','Yes','TV',NULL,'Soundbar','1','Soundbar','1',NULL,'None Needed',NULL),
('Scott Lab','SO W259','Teaching Lab',NULL,NULL,'MAE',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Level 1',NULL,NULL,NULL,'N/A',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'None Needed',NULL),
('Scott Lab','SO W260','Mixed Purpose',NULL,NULL,'MAE',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Level 1',NULL,NULL,NULL,'N/A',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'None Needed',NULL),
('Scott Lab','SO W268','Computer Lab','No AV',NULL,'MAE',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N/A',NULL,NULL,NULL,'0',NULL,'0',NULL,'None Needed',NULL),
('Scott Lab','SO W269','Computer Lab','No AV',NULL,'MAE',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N/A',NULL,NULL,NULL,'0',NULL,'0',NULL,'None Needed',NULL),
('Scott Lab','SO W270','Computer Lab','No AV',NULL,'MAE',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N/A',NULL,NULL,NULL,'0',NULL,'0',NULL,'None Needed',NULL),
('Scott Lab','SO W279','Grad Office','No AV',NULL,'MAE',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N/A',NULL,NULL,NULL,'0',NULL,'0',NULL,'None Needed',NULL),
('Scott Lab','SO W280/282','Mixed Purpose','ETS','ETS','MAE','20','2017*',NULL,'Swipe',NULL,NULL,'None','None',NULL,'50000',NULL,'2','1','Yes','Projector',NULL,'Soundbar','1','Soundbar','1',NULL,'Needs Custom - see pics - bose remote',NULL),
('Scott Lab','SO W286','Computer Lab','No AV',NULL,'MAE',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N/A',NULL,NULL,NULL,'0',NULL,'0',NULL,'None Needed',NULL),
('Scott Lab','SO W294',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Scott Lab','SO W295',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
